image: node:8.6.0

services:
  - postgres:9.5.0

stages:
  - all_tests
  - deploy_api_dev

all_tests:
  stage: all_tests
  only:
    - master
    - develop
  script:
    - cd server
    - npm install
    - npm run lint

deploy_api_dev:
  stage: deploy_api_dev
  only:
    - cicd/port-env-fix
  image: ruby:latest
  before_script:
    - cd server
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=feup-link-dev-api --api-key=$HEROKU_API_KEY
  environment:
    name: production
