image: node:8.6.0

services:
  - postgres:9.5.0

stages:
  - all_tests
  - deploy_api_dev

all_tests:
  stage: all_tests
  only:
    - master
    - develop
  script:
    - cd server
    - npm install
    - npm run lint

deploy_api_dev:
  stage: deploy_api_dev
  only:
    - cicd/port-env-fix
  script:
    - git config --global user.email "lgp1718c03@gmail.com"
    - git config --global user.name "FEUPLink"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/feup-link-dev-api.git
    - git checkout master
    - git subtree pull --prefix server heroku master
    - git subtree push --prefix server heroku master
    - git remote remove heroku
  environment:
    name: production
